config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'

  resources :books do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: {maximum: 255}
  validates :description, presence: true
  validates :year, presence: true
  validates :author, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user, optional: true

  validates :book, presence: true
  validates :body, presence: true

  validates :user_name, presence: true, unless: -> {'user.present?'}

  def user_name
    if user.present?
      user.name
    else
      super
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: {minimum: 2}, uniqueness: true

  has_many :books, dependent: :destroy
  has_many :comments

  before_validation :set_name, on: :create

  private

  def set_name
    self.name = "Пользователь библиотеки №#{rand(777)}" if self.name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_user_can_edit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [:password, :password_confirmation, :current_password]
    )
  end

  def current_user_can_edit?(book)
    user_signed_in? && book.user == current_user
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  before_action :set_book

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'The book was added successfully.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'The book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to book_url, notice: 'The book was successfully deleted'
  end

  private

  def set_book
    @book = Book.find_by(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :year, :author)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  before_action :set_book, except: [:index, :new, :create]
  before_action :set_current_user_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
    @new_comment = @book.comments.build(params[:comment])
  end

  def new
    @book = current_user.books.build
  end

  def edit
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to @book, notice: 'The books was added successfully.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'The books was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'The books was successfully deleted'
  end

  private

  def set_current_user_book
    @book = current_user.books.find(params[:id])
  end

  def set_book
    @book = Book.find_by_id(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :year, :author, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_book, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  def create
    @new_comment = @book.comments.build(comment_params)
    @new_comment.user = current_user

    if check_captcha(@new_comment) && @new_comment.save
      notify_owner(@book,@new_comment)

      redirect_to @book, notice: 'comment was successful created'
    else
      render :'books/show'
    end
  end

  def destroy
    mesage = {noice: ('comment was successful destroyed')}

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      mesage = {alert: ('error when a destroyed comment')}
    end

    redirect_to @book, mesage
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def set_comment
    @comment = @book.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body,:user_name)
  end

  def notify_owner(book, comment)
    owner_email = [book.user.email].uniq

    owner_email.each do |mail|
      BookMailer.comment(book, comment, mail).deliver_now
    end
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user = User.update(user_params)
      redirect_to user_url
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find_by(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user

  def show
  end

  def edit
  end

  def update
    if @user = User.update(user_params)
      redirect_to user_url
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'The user was successfully deleted'
  end

  private

  def set_current_user
    @user = current_user
  end

  def set_user
    @user = User.find_by(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book/index.html.erb
<div class="text-center">
  <% @books.each do |book| %>
    <div>
        <p><%= link_to book.title, book_path(book) %></p>
        <p>Автор <%= book.author %></p>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-8 offset-2">
    <div class="text-center">
      <h3>Изменить информацию о книги</h3>
    </div>
    <%= simple_form_for @book do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :image %>
      <%= f.input :year %>
      <%= f.input :author %>
      <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="text-center">
  <div class="m-1 p-1">
    <h1>Книги</h1>
  </div>

  <% @books.each do |book| %>
    <div class="row justify-content-center m-2 p-2">
      <div class="col-4">
        <p><%= image_tag book.image.thumb.url if book.image_url %></p>
      </div>
      <div class="col-4">
        <p><%= link_to book.title, book_path(book[:id]) %></p>
        <p>Автор <%= book.author %></p>
      </div>
    </div>
  <% end %>

  <div class="buffer-both">
    <%= link_to 'Добавить книгу', new_book_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/books/new.html.erb
<div class="row">
  <div class="col-8 offset-2">
    <div class="text-center">
      <h3>Добавить новую книгу</h3>
    </div>
    <%= simple_form_for @book do |f| %>
      <%= f.input :title %>
      <%= f.input :image %>
      <%= f.input :description %>
      <%= f.input :year %>
      <%= f.input :author %>
      <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="text-center">
  <div class="m-1 p-1">
    <h1><%= @book.title %></h1>
  </div>
  <div class="row justify-content-center m-2 p-2">
    <div class="col-4">
      <p><%=image_tag @book.image.url if @book.image_url %></p>
    </div>
    <div class="col-4">
    <p><%= @book.description %></p>
    <p><%= @book.author %></p>
    <p><%= @book.year %></p>
  </div>
  </div>

  <div>
    <p>Добавил книгу <%= link_to @book.user.name, user_path(@book) %></p>
  </div>

  <div class="row justify-content-center m-2 p-2">
    <div class="col-8">
      <div class="buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @book.comments.build} %>
        <div class="buffer-both">
          <%= render partial: 'comments/comment',
                     collection: @book.comments.except(@new_comment) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="buffer-bottom">
  <br>
  <p><%= comment.body %></p>
  <p>
    <span>
      <% if comment.user.present? %>
        <%= render partial: 'users/user', object: comment.user %>
      <% else %>
        <em><strong><%= comment.user_name %></strong></em>
      <% end %>
    </span>
    <em><%= l comment.created_at, format: :short %></em>
    <% if current_user_can_edit?(comment) %>
      <%= link_to(
            'Удалить', book_comment_path(comment.book, comment), data: {confirm: ('Are you sure?')},
            method: :delete, class: "btn btn-mini btn-secondary"
          ) %>
    <% end %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@book, comment] do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: comment} %>

  <div class="form-group">
    <%= f.label "Написать коментарий", :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <% unless user_signed_in? %>
    <div class="form-group">
      <%= f.label "Ваше имя", :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>
    </div>
  <% end %>

  <%# Captcha helper %>
  <div class="btn-group pb-3 m-3">
    <%= recaptcha_tags unless current_user.present? %>
  </div>

  <div class="actions">
    <%= f.submit 'Отправить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-lg navbar-light bg-light" >
    <div class="container">
      <%= link_to "Библиотека", root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <% if user_signed_in? %>
            <li class="nav-link"><%= link_to 'Профиль', current_user %></li>
            <li class="nav-link"><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li class="nav-link"><%= link_to 'Войти', new_user_session_path %></li>
            <li class="nav-link"><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
      </div>
      <div class="col-lg-3">
      </div><!--/span-->
    </div><!--/row-->
  </div> <!-- /container -->
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>
<% if errors.any? %>
  <div class="alert alert-danger">
    <div class="lead buffer-bottom">
      Найдено ошибок <%= errors.count %>
    </div>

    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">

  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-8 offset-2">
    <div class="text-center">
      <h1>Редактирование профиля</h1>
    </div>
    <%= simple_form_for @user do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
    <p class="buffer-top py-2">
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <div class="m-1 p-1">
    <h1><%= @user.name %></h1>
  </div>

  <% @user.books.each do |book| %>
    <div class="row justify-content-center m-2 p-2">
      <div class="col-4">
        <p><%=image_tag book.image.url if book.image_url%></p>
      </div>
      <div class="col-4">
        <p><%= book.title %></p>
        <p><%= book.description %></p>
        <p><%= book.author %></p>
        <p><%= book.year %></p>
        <p><%= link_to "Редактировать книгу", edit_book_path(book),
                       class: 'btn btn-primary'%></p>
        <p><%= link_to "Удалить", book, data: {confirm: ('Are you sure?')},
                        method: :delete, class: "btn btn-danger" %></p>
      </div>
    </div>
  <% end %>

  <% if @user == current_user %>
    <p class="buffer-top"><%= link_to "Редактировать профиль", edit_user_path(@user),
                class: 'btn btn-primary' %></p>
    <p><%= link_to "Удалить", @user, data: {confirm: ('Are you sure?')},
                   method: :delete, class: "btn btn-danger" %></p>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>